# Enviorement variables for all `cargo...` commands
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="rust_axum=debug"

# -- Service Enviorment Variables
# IMPORTANT
#   For cargo command only.
#   For deployed env, should be managed container
#   (e.g., Kubernetes)

## -- Secrets
# Keys and password below are for localhost dev ONLY.
# e.g, "root" type passwords.
# i.e, Encryption not needed.

SERVICE_DB_URL = "postgres://app_user:dev_only_pwd@localhost:5432/app_db"

## -- ConfigMap

# This will be relative to Cargo.toml
# In deployed images, probably use absolute path.

SERVICE_WEB_FOLDER = "web-folder/"